use DDL;
/*CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID INT PRIMARY KEY,  
    DEPARTMENT_NAME VARCHAR(50) NOT NULL,  
    MANAGER_ID INT NULL,  
    LOCATION_ID INT NULL  
);*/

/*CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT PRIMARY KEY,  
    FIRST_NAME VARCHAR(50) NOT NULL,  
    LAST_NAME VARCHAR(50) NOT NULL,  
    EMAIL VARCHAR(100) UNIQUE NOT NULL,  
    PHONE_NUMBER VARCHAR(20) NULL, 
    HIRE_DATE DATE NOT NULL,  
    JOB_ID VARCHAR(10) NOT NULL,  
    SALARY DECIMAL(10,2) NOT NULL,  
    COMMISSION_PCT DECIMAL(5,2) NULL, 
    MANAGER_ID INT NULL,  
    DEPARTMENT_ID INT NULL,  
    CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
    CONSTRAINT FK_EMP_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);*/
--1
/*CREATE TABLE TRG_DEPT (
    ID INT NOT NULL,
    NAME VARCHAR(25) NOT NULL
);*/
--2
/*SELECT DEPARTMENT_ID AS ID, DEPARTMENT_NAME AS NAME 
INTO DEPT101 
FROM DEPARTMENTS;*/
--3
/*CREATE TABLE TRG_EMP (
    ID INT NOT NULL,  
    LAST_NAME VARCHAR(25) NOT NULL,  
    FIRST_NAME VARCHAR(25) NOT NULL,  
    DEPT_ID INT NOT NULL 
);*/
--4
/*ALTER TABLE TRG_EMP 
ALTER COLUMN LAST_NAME VARCHAR(50) NOT NULL;

EXEC sp_columns TRG_EMP;*/
--5
/*SELECT EMPLOYEE_ID AS ID, 
       FIRST_NAME, 
       LAST_NAME, 
       SALARY, 
       DEPARTMENT_ID AS DEPT_ID
INTO TRG_EMPLOYEES
FROM EMPLOYEES;
*/
--6
--DROP TABLE TRG_EMP;
--7
--EXEC sp_rename 'TRG_EMPLOYEES', 'TRG_EMP';
--EXEC sp_columns TRG_EMP;
--ALTER TABLE TRG_EMP 
--DROP COLUMN FIRST_NAME;
--EXEC sp_columns TRG_EMP;






